import { Open_Sans } from "next/font/google"
import "./globals.css"
import NavBar from "@/components/NavBar"
const opensans = Open_Sans({ subsets: ["latin"], weight: ["variable"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={opensans.className}>
        <NavBar />
        {children}</body>
    </html>
  )
}
