import { Fira_Sans } from "next/font/google"
import "./globals.css"
import NavBar from "@/components/NavBar"
const firasans = Fira_Sans({ subsets: ["latin"], weight: ["100", "200", "300", "400"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={firasans.className}>
        <NavBar />
        {children}</body>
    </html>
  )
}
